name: Qt SQL Plugin Installer
description: 'Install the sql plugins from the qt sources'
inputs:
  working-directory:
    description: "Path to the working directory"
    required: false
    default: $RUNNER_TEMP
  mysql-install:
    description: Install the mysql plugin 
    required: false
    default: "false"
  mysql-path:
    description: Path to the MySql installation. Must be contain lib and include directory. only relevant for windows
    required: false
    default: ""
  qt-version:
    description: Used commit of qt sources
    required: false
    default: 5.15.2
runs:
  using: node12
  main: index.js
