name: Qbs-Tests

on: push

jobs:

  windows:
    name: "test on windows"
    strategy:
      matrix:
        qt-version: [5.15.2, 6.1.3,  6.2.0 ]
    runs-on: windows-latest

    steps:
      - name: Start MySQL
        uses: fettpet/setup-mysql@v1
        with:
          mysql-version: 8.0
          install-directory: "${{ runner.workspace }}\\MySQL"
          username: test 
          password: test

      - name: Start PostgreSQL 
        run: |
          $pgService = Get-Service -Name postgresql*
          Set-Service -InputObject $pgService -Status running -StartupType automatic
          Start-Process -FilePath "$env:PGBIN\pg_isready" -Wait -PassThru

      - name: Setup Postgres 
        run: |
          echo "PGROOT=$PGROOT" >> $GITHUB_ENV
          echo "$GITHUB_ENV"
        shell: bash

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.qt-version}}
          
      - name: install mvsc
        uses: ilammy/msvc-dev-cmd@v1
        with:
          toolset: "14.29"
          
      - uses: actions/checkout@v2

      - name: Install Plugin
        uses: ./
        with:
          mysql-install: true
          mysql-path: "${{ runner.workspace }}\\MySQL"
          postgresql-install: true
          postgresql-path: "${{ env.PGROOT }}"
          qt-version: ${{ matrix.qt-version}}
      
      - name: run tests
        run: | 
          $env:Path += ";${{ runner.workspace }}/MySQL/lib;${{ runner.workspace }}/MySQL/include;"
          set QT_FORCE_STDERR_LOGGING=1
          cd ${{ runner.workspace }}/qt_sql_plugin_installer/test
          mkdir build
          cd build 
          cmake .. -DQT_VERSION=${{ matrix.qt-version}} -DMYSQL_USER:STRING=test -DMYSQL_PASSWORD:STRING=test -DPOSTGRESQL_USER:STRING=postgres -DPOSTGRESQL_PORT:STRING=5432 -DPOSTGRESQL_HOST:STRING=localhost
          cmake --build .
          ctest --output-on-failure

  linux:
    name: "test on linux"
    strategy:
      matrix:
        qt-version: [5.15.2, 6.1.3,  6.2.0 ]
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Start MySQL
        uses: fettpet/setup-mysql@v1
        with:
          mysql-version: 8.0
          install-directory: "${{ runner.workspace }}\\MySQL"
          username: test 
          password: test

      
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.qt-version}}
          
      - name: install cmake, clang12, ninja
        run: |
          sudo apt-get update -y
          sudo apt-get install -y clang-12 llvm-12
          
      - uses: actions/checkout@v2

      - name: Setup Postgres 
        run: |
          echo "PGROOT=$PGROOT" >> $GITHUB_ENV
          echo "$GITHUB_ENV"
        shell: bash

      - name: Install Plugin
        uses: ./
        with:
          mysql-install: true
          postgresql-install: true
          qt-version: ${{ matrix.qt-version}}
      
      - name: Show plugin 
        run: 
          ls -R ${{ runner.workspace }}/qtbase/src/plugins/sqldrivers/

      - name: run tests
        run: | 
          set QT_FORCE_STDERR_LOGGING=1
          cd ${{ runner.workspace }}/qt_sql_plugin_installer/test
          mkdir build
          cd build 
          cmake .. -DQT_VERSION=${{ matrix.qt-version}} -DMYSQL_USER:STRING=test -DMYSQL_PASSWORD:STRING=test -DPOSTGRESQL_USER:STRING=postgres -DPOSTGRESQL_PASSWORD:STRING=postgres -DPOSTGRESQL_PORT:STRING=5432 -DPOSTGRESQL_HOST:STRING=localhost
          cmake --build .
          ctest --output-on-failure
