name: Qbs-Tests

on: push

jobs:

  windows:
    name: "test on windows"
    
    runs-on: windows-latest

    steps:
      - name: Start MySQL
        uses: fettpet/setup-mysql@v1
        with:
          mysql-version: 8.0
          install-directory: "${{ runner.workspace }}\\MySQL"
      
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: "5.15.2"
          
      - name: install mvsc
        uses: ilammy/msvc-dev-cmd@v1
        with:
          toolset: "14.29"
          
      - uses: actions/checkout@v2

      - name: Add Postgres 
        run: |
          echo "PGROOT=$PGROOT" >> $GITHUB_ENV
          echo "$GITHUB_ENV"
        shell: bash

      - name: Install Plugin
        uses: ./
        with:
          mysql-install: true
          mysql-path: "${{ runner.workspace }}\\MySQL"
          postgresql-install: true
          postgresql-path: "${{ env.PGROOT }}"

  linux:
    name: "test on linux"
    
    runs-on: ubuntu-latest

    steps:
      - name: Start MySQL
        uses: fettpet/setup-mysql@v1
        with:
          mysql-version: 8.0
          install-directory: "${{ runner.workspace }}\\MySQL"
          username: test 
          password: test
      
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: "5.15.2"
          
      - name: install cmake, clang12 
        run: |
          sudo apt-get update -y
          sudo apt-get install -y clang-12 llvm-12 cmake 
          
      - uses: actions/checkout@v2

      - name: Add Postgres 
        run: |
          echo "PGROOT=$PGROOT" >> $GITHUB_ENV
          echo "$GITHUB_ENV"
        shell: bash

      - name: Install Plugin
        uses: ./
        with:
          mysql-install: true
          postgresql-install: true

      - name: run tests
        run: | 
          cd ${{ runner.workspace }}/qt_sql_plugin_installer/test
          mkdir build
          cd build 
          cmake .. -DMYSQL_USER:STRING=test -DMYSQL_PASSWORD:STRING=test
          make 
          make test
      - name: run last 
        if: ${{ always()}}
        run: | 
          cat /home/runner/work/qt_sql_plugin_installer/qt_sql_plugin_installer/test/build/Testing/Temporary/LastTest.log